#include "editor.hpp"

#if defined(ERHE_WINDOW_LIBRARY_SDL)
#   include <SDL3/SDL_main.h>
#endif

#if defined(ERHE_OS_ANDROID)
#   include "erhe_file/file.hpp"
#   include <SDL3/SDL_system.h>
#   include <unistd.h>
#endif

auto main(int, char**) -> int
{
#if defined(ERHE_OS_ANDROID)
    // Android starts the process at cwd "/", which is read-only and outside
    // the app sandbox. Move to internal storage so relative writes
    // (spirv_cache/, generated configs) land under /data/data/<pkg>/files/.
    if (const char* base = SDL_GetAndroidInternalStoragePath()) {
        ::chdir(base);
    }

    // First-launch migration: copy every file listed in the bundled manifest
    // (config/* and res/editor/assets/*) from the APK to the writable cwd,
    // unless the destination already exists. config must be writable so
    // save_config writes from the Settings window round-trip correctly;
    // assets must be writable because this is an editor -- assets are
    // read/write and the asset browser enumerates them with std::filesystem,
    // which only sees the migrated real files (not APK assets). After this,
    // erhe::file::read tries the writable copy first (then falls back to APK
    // assets). The manifest is generated by stageErheAssets in
    // android-project/app/build.gradle.
    (void)erhe::file::migrate_android_assets_to_writable("erhe_migrate_manifest.txt");
#endif
    editor::run_editor();
    return 0;
}
