#include "crash_handler.hpp"
#include "editor.hpp"

#include <cxxopts.hpp>

#include <string>

#if defined(ERHE_WINDOW_LIBRARY_SDL)
#   include <SDL3/SDL_main.h>
#endif

#if defined(ERHE_OS_ANDROID)
#   include "erhe_file/file.hpp"
#   include <SDL3/SDL_system.h>
#   include <unistd.h>
#endif

auto main(int argc, char** argv) -> int
{
    // Install before anything else so a fatal abort() (e.g. OpenNL's nl_assert
    // during a Geogram remesh) writes a minidump and exits instead of hanging on
    // a modal Abort / Retry / Ignore dialog.
    editor::install_crash_handler();

    // Command-line options.
    //   --commands overrides the startup script that sets up the scene (e.g.
    //     --commands config/editor/commands_cuboctahedron.json loads a single-mesh
    //     debug scene instead of the default).
    //   --scene loads a saved scene directory bundle (.erhescene) on startup
    //     instead of building a scene procedurally, e.g.
    //     --scene "res/editor/scenes/Default Scene.erhescene".
    //   --no-scene starts with an empty editor: no procedural default scene and no
    //     scene load (takes precedence over --scene).
    // Unknown options are ignored (the OS / launcher may append its own), and any
    // parse error falls back to the defaults rather than failing to start.
    std::string startup_commands_path{"config/editor/commands.json"};
    std::string startup_scene_path{};
    bool        no_startup_scene{false};
    try {
        cxxopts::Options options{"editor", "erhe editor"};
        options.add_options()
            ("commands", "Startup commands script (scene setup) JSON path", cxxopts::value<std::string>()->default_value("config/editor/commands.json"))
            ("scene",    "Scene directory bundle (.erhescene) to load on startup instead of building the default scene", cxxopts::value<std::string>()->default_value(""))
            ("no-scene", "Start with an empty editor: no procedural default scene and no scene load (overrides --scene)")
            ("h,help",   "Print usage");
        options.allow_unrecognised_options();
        const cxxopts::ParseResult result = options.parse(argc, argv);
        if (result.count("help") != 0) {
            std::printf("%s\n", options.help().c_str());
            return 0;
        }
        startup_commands_path = result["commands"].as<std::string>();
        startup_scene_path    = result["scene"].as<std::string>();
        no_startup_scene      = (result.count("no-scene") != 0);
    } catch (const std::exception&) {
        // Keep the default startup paths on any parse failure.
    }

#if defined(ERHE_OS_ANDROID)
    // Android starts the process at cwd "/", which is read-only and outside
    // the app sandbox. Move to internal storage so relative writes
    // (spirv_cache/, generated configs) land under /data/data/<pkg>/files/.
    if (const char* base = SDL_GetAndroidInternalStoragePath()) {
        ::chdir(base);
    }

    // First-launch migration: copy every file listed in the bundled manifest
    // (config/* and res/editor/assets/*) from the APK to the writable cwd,
    // unless the destination already exists. config must be writable so
    // save_config writes from the Settings window round-trip correctly;
    // assets must be writable because this is an editor -- assets are
    // read/write and the asset browser enumerates them with std::filesystem,
    // which only sees the migrated real files (not APK assets). After this,
    // erhe::file::read tries the writable copy first (then falls back to APK
    // assets). The manifest is generated by stageErheAssets in
    // android-project/app/build.gradle.
    (void)erhe::file::migrate_android_assets_to_writable("erhe_migrate_manifest.txt");
#endif
    editor::run_editor(startup_commands_path, startup_scene_path, no_startup_scene);
    return 0;
}
