from erhe_codegen import *

struct("Material",
    version=4,
    fields=[
        field("name",             String,
            added_in=1,
            short_desc="Material name",
            long_desc="Human-readable display name for this material",
            visible=True,
            default='""',
        ),
        field("albedo",           Vec4,
            added_in=1,
            short_desc="Albedo color",
            long_desc="Base color in linear RGBA",
            visible=True,
            default="0.5f, 0.5f, 0.5f, 1.0f",
        ),
        field("metallic",         Float,
            added_in=1,
            short_desc="Metallic factor",
            long_desc="0 = dielectric, 1 = metal",
            visible=True,
            default="0.0f",
            ui_min="0.0f", ui_max="1.0f",
            hard_min="0.0f", hard_max="1.0f",
        ),
        field("roughness",        Float,
            added_in=1,
            short_desc="Roughness factor",
            default="0.5f",
            ui_min="0.0f", ui_max="1.0f",
            hard_min="0.0f", hard_max="1.0f",
        ),
        field("emissive",         Vec3,
            added_in=2,
            short_desc="Emissive color",
            long_desc="Linear RGB emissive contribution",
            visible=True,
            default="0.0f, 0.0f, 0.0f",
        ),
        field("texture_paths",    Vector(String),
            added_in=1,
            short_desc="Texture paths",
        ),
        field("opacity",          Float,
            added_in=2, removed_in=3,
            short_desc="Opacity (deprecated)",
            long_desc="Replaced by albedo alpha channel in v3",
            visible=True,
            default="1.0f",
            ui_min="0.0f", ui_max="1.0f",
            hard_min="0.0f", hard_max="1.0f",
        ),
        field("uv_scales",        Array(Float, 4),
            added_in=3,
            short_desc="UV channel scales",
            default="1.0f, 1.0f, 1.0f, 1.0f",
        ),
        field("blend_mode",       EnumRef("Blend_mode"),
            added_in=4,
            short_desc="Blend mode",
            default="Blend_mode::opaque",
        ),
    ],
)
