from erhe_codegen import *

struct("Settings",
    version=3,
    fields=[
        field("window_width",   Int,
            added_in=1,
            short_desc="Window width",
            long_desc="Width of the application window in pixels",
            default="1920",
            ui_min="320", ui_max="7680",
            hard_min="320", hard_max="7680",
        ),
        field("window_height",  Int,
            added_in=1,
            short_desc="Window height",
            default="1080",
            ui_min="240", ui_max="4320",
            hard_min="240", hard_max="4320",
        ),
        field("fullscreen",     Bool,
            added_in=1,
            short_desc="Fullscreen mode",
            default="false",
        ),
        field("render_scale",   Float,
            added_in=2,
            short_desc="Render scale",
            long_desc="Resolution scale factor (1.0 = native)",
            default="1.0f",
            ui_min="0.25f", ui_max="2.0f",
            hard_min="0.1f", hard_max="4.0f",
        ),
        field("username",       String,
            added_in=1,
            short_desc="User name",
            default='""',
        ),
        field("gamma",          Float,
            added_in=1, removed_in=3,
            short_desc="Gamma (deprecated)",
            long_desc="Replaced by render_scale in v2",
            default="2.2f",
        ),
        field("custom_dpi",     Optional(Float),
            added_in=3,
            short_desc="Custom DPI override",
            long_desc="If set, overrides system DPI detection",
        ),
        field("display_name",   Optional(String),
            added_in=3,
            short_desc="Display name override",
        ),
    ],
)
