// Verifies doc/catmull_clark.md item 11: in an iterated subdivision chain,
// running the intermediate iterations with Post_processing::structural_only
// (connect + build_edges + centroids, skipping smooth-vertex-normal and
// facet-texcoord regeneration) must not change the final iteration's output:
// the final full_default post-processing re-derives the regenerated channels
// from positions + topology, and the preserved (interpolated) channels do not
// depend on the regenerated ones.

#include "erhe_geometry/geometry.hpp"
#include "erhe_geometry/operation/post_processing.hpp"
#include "erhe_geometry/operation/subdivision/catmull_clark_subdivision.hpp"
#include "erhe_geometry/operation/subdivision/sqrt3_subdivision.hpp"
#include "erhe_geometry/shapes/regular_polyhedron.hpp"

#include <gtest/gtest.h>

#include <memory>

using erhe::geometry::Geometry;
using erhe::geometry::Attribute_present;
using erhe::geometry::get_pointf;
using erhe::geometry::operation::Component_remap;
using erhe::geometry::operation::Post_processing;

namespace {

using Subdivide_fn = void (*)(const Geometry&, Geometry&, const std::set<GEO::index_t>*, Component_remap*, Post_processing);

// A processed cube with seeded preserved channels: vertex colors, vertex
// texcoords and corner colors are interpolated (never regenerated by
// process()), so they must flow through the chain identically whichever
// post-processing the intermediate iterations run.
auto make_seeded_cube() -> std::unique_ptr<Geometry>
{
    std::unique_ptr<Geometry> geometry = std::make_unique<Geometry>("cube");
    erhe::geometry::shapes::make_cube(geometry->get_mesh(), 1.0f);
    const uint64_t flags =
        Geometry::process_flag_connect |
        Geometry::process_flag_build_edges |
        Geometry::process_flag_compute_facet_centroids |
        Geometry::process_flag_compute_smooth_vertex_normals |
        Geometry::process_flag_generate_facet_texture_coordinates;
    geometry->process({.flags = flags});

    erhe::geometry::Mesh_attributes& attributes = geometry->get_attributes();
    const GEO::Mesh& mesh = geometry->get_mesh();
    for (GEO::index_t vertex : mesh.vertices) {
        const float f = static_cast<float>(vertex);
        attributes.vertex_color_0   .set(vertex, GEO::vec4f{0.125f * f, 0.25f * f, 0.03125f * f, 1.0f});
        attributes.vertex_texcoord_0.set(vertex, GEO::vec2f{0.1f * f, 0.2f * f});
    }
    for (GEO::index_t corner : mesh.facet_corners) {
        const float f = static_cast<float>(corner);
        attributes.corner_color_0.set(corner, GEO::vec4f{0.0625f * f, 0.015625f * f, 0.5f, 1.0f});
    }
    return geometry;
}

auto run_chain(const Geometry& source, const int iterations, const bool structural_intermediates, const Subdivide_fn subdivide) -> std::unique_ptr<Geometry>
{
    std::unique_ptr<Geometry> current{};
    const Geometry* input = &source;
    for (int i = 0; i < iterations; ++i) {
        const Post_processing post_processing_level =
            (structural_intermediates && ((i + 1) < iterations))
                ? Post_processing::structural_only
                : Post_processing::full_default;
        std::unique_ptr<Geometry> next = std::make_unique<Geometry>("subdivided");
        subdivide(*input, *next.get(), nullptr, nullptr, post_processing_level);
        current = std::move(next);
        input = current.get();
    }
    return current;
}

template <typename T>
void expect_attribute_identical(const Attribute_present<T>& a, const Attribute_present<T>& b, const GEO::index_t count, const char* name)
{
    for (GEO::index_t key = 0; key < count; ++key) {
        const std::optional<T> value_a = a.try_get(key);
        const std::optional<T> value_b = b.try_get(key);
        ASSERT_EQ(value_a.has_value(), value_b.has_value()) << name << " presence differs at " << key;
        if (!value_a.has_value()) {
            continue;
        }
        for (GEO::index_t i = 0; i < T::dim; ++i) {
            // Exact comparison on purpose: both chains must perform the same
            // float operations in the same order on these channels.
            EXPECT_EQ(value_a.value()[i], value_b.value()[i]) << name << " differs at " << key << " component " << i;
        }
    }
}

void expect_final_output_identical(Geometry& full, Geometry& structural)
{
    const GEO::Mesh& full_mesh       = full.get_mesh();
    const GEO::Mesh& structural_mesh = structural.get_mesh();

    ASSERT_EQ(full_mesh.vertices.nb(),      structural_mesh.vertices.nb());
    ASSERT_EQ(full_mesh.facets.nb(),        structural_mesh.facets.nb());
    ASSERT_EQ(full_mesh.facet_corners.nb(), structural_mesh.facet_corners.nb());
    ASSERT_EQ(full_mesh.edges.nb(),         structural_mesh.edges.nb());

    for (GEO::index_t vertex : full_mesh.vertices) {
        const GEO::vec3f p_full       = get_pointf(full_mesh.vertices, vertex);
        const GEO::vec3f p_structural = get_pointf(structural_mesh.vertices, vertex);
        EXPECT_EQ(p_full.x, p_structural.x) << "position x differs at vertex " << vertex;
        EXPECT_EQ(p_full.y, p_structural.y) << "position y differs at vertex " << vertex;
        EXPECT_EQ(p_full.z, p_structural.z) << "position z differs at vertex " << vertex;
    }

    const erhe::geometry::Mesh_attributes& a = full.get_attributes();
    const erhe::geometry::Mesh_attributes& b = structural.get_attributes();
    const GEO::index_t vertex_count = full_mesh.vertices.nb();
    const GEO::index_t corner_count = full_mesh.facet_corners.nb();
    const GEO::index_t facet_count  = full_mesh.facets.nb();

    // Channels regenerated by the final full post-processing.
    expect_attribute_identical(a.vertex_normal_smooth, b.vertex_normal_smooth, vertex_count, "vertex_normal_smooth");
    expect_attribute_identical(a.corner_texcoord_1,    b.corner_texcoord_1,    corner_count, "corner_texcoord_1");
    expect_attribute_identical(a.facet_centroid,       b.facet_centroid,       facet_count,  "facet_centroid");

    // Preserved channels carried by interpolation only.
    expect_attribute_identical(a.vertex_color_0,       b.vertex_color_0,       vertex_count, "vertex_color_0");
    expect_attribute_identical(a.vertex_texcoord_0,    b.vertex_texcoord_0,    vertex_count, "vertex_texcoord_0");
    expect_attribute_identical(a.corner_color_0,       b.corner_color_0,       corner_count, "corner_color_0");
}

} // anonymous namespace

TEST(SubdivisionChain, CatmullClark_StructuralIntermediates_FinalOutputIdentical)
{
    std::unique_ptr<Geometry> cube = make_seeded_cube();
    std::unique_ptr<Geometry> full       = run_chain(*cube.get(), 3, false, erhe::geometry::operation::catmull_clark_subdivision);
    std::unique_ptr<Geometry> structural = run_chain(*cube.get(), 3, true,  erhe::geometry::operation::catmull_clark_subdivision);
    expect_final_output_identical(*full.get(), *structural.get());
}

TEST(SubdivisionChain, Sqrt3_StructuralIntermediates_FinalOutputIdentical)
{
    std::unique_ptr<Geometry> cube = make_seeded_cube();
    std::unique_ptr<Geometry> full       = run_chain(*cube.get(), 3, false, erhe::geometry::operation::sqrt3_subdivision);
    std::unique_ptr<Geometry> structural = run_chain(*cube.get(), 3, true,  erhe::geometry::operation::sqrt3_subdivision);
    expect_final_output_identical(*full.get(), *structural.get());
}
