from erhe_codegen import *

struct("Ddgi_config",
    reflect=True,
    version=1,
    short_desc="DDGI",
    long_desc="Dynamic diffuse global illumination (doc/ddgi-plan.md). A single scene-wide probe volume is auto-fitted to the content bounding box; probes are traced with ray queries, blended into octahedral irradiance and distance atlases, and sampled by the forward shader in place of the flat ambient term. Requires GPU ray query support; the feature stays off on backends without it.",
    developer=False,
    fields=[
        field(
            "enabled",
            Bool,
            added_in=1,
            default="false",
            short_desc="Enabled",
            long_desc="Master switch. Off restores the flat ambient term for every non-lightmapped draw and skips all DDGI GPU work.",
            visible=True,
            developer=False
        ),
        field(
            "probe_spacing_m",
            Float,
            added_in=1,
            default="1.5f",
            short_desc="Probe spacing (m)",
            long_desc="Target world-space distance between adjacent probes. The grid dimensions are the padded content bounding box divided by this, so smaller spacing means more probes (and more GPU cost) at higher spatial detail. The actual spacing per axis is the box extent divided by the resulting probe count, so it can differ slightly per axis.",
            visible=True,
            developer=False,
            ui_min="0.1f",
            ui_max="16.0f",
            hard_min="0.01f"
        ),
        field(
            "volume_padding_m",
            Float,
            added_in=1,
            default="1.0f",
            short_desc="Volume padding (m)",
            long_desc="Amount the content bounding box is grown by on every side before the probe grid is fitted. Padding puts a probe layer outside the geometry so surfaces on the box boundary still have probes on both sides to interpolate between.",
            visible=True,
            developer=False,
            ui_min="0.0f",
            ui_max="16.0f",
            hard_min="0.0f"
        ),
        field(
            "max_probes",
            Int,
            added_in=1,
            default="4096",
            short_desc="Max probes",
            long_desc="Upper bound on the total probe count. When the spacing would produce more probes than this, the spacing is scaled up until the grid fits. Guards against a huge scene silently allocating gigabytes of probe atlases.",
            visible=True,
            developer=False,
            ui_min="8",
            ui_max="65536",
            hard_min="8"
        ),
        field(
            "rays_per_probe",
            Int,
            added_in=1,
            default="128",
            short_desc="Rays per probe",
            long_desc="Rays traced per probe per update. Higher converges faster and with less noise, at linearly higher trace cost. Rounded up to a multiple of the trace workgroup size.",
            visible=True,
            developer=False,
            ui_min="16",
            ui_max="512",
            hard_min="8"
        ),
        field(
            "irradiance_texels",
            Int,
            added_in=1,
            default="6",
            short_desc="Irradiance texels",
            long_desc="Octahedral resolution of one probe's irradiance tile, excluding the 1-texel border. The classic DDGI value is 6 (an 8x8 tile with borders).",
            visible=True,
            developer=True,
            ui_min="4",
            ui_max="16",
            hard_min="2"
        ),
        field(
            "distance_texels",
            Int,
            added_in=1,
            default="14",
            short_desc="Distance texels",
            long_desc="Octahedral resolution of one probe's distance tile, excluding the 1-texel border. Higher than the irradiance resolution because the Chebyshev visibility test needs sharper distance detail to stop light leaking through thin geometry. The classic DDGI value is 14 (a 16x16 tile with borders).",
            visible=True,
            developer=True,
            ui_min="6",
            ui_max="32",
            hard_min="2"
        ),
        field(
            "hysteresis",
            Float,
            added_in=1,
            default="0.97f",
            short_desc="Hysteresis",
            long_desc="Temporal blend weight kept from the previous probe state each update. Higher is smoother and less noisy but slower to react to light and geometry changes; 0 replaces the probe contents every update.",
            visible=True,
            developer=False,
            ui_min="0.0f",
            ui_max="0.999f",
            hard_min="0.0f",
            hard_max="0.999f"
        ),
        field(
            "depth_sharpness",
            Float,
            added_in=1,
            default="50.0f",
            short_desc="Depth sharpness",
            long_desc="Exponent of the cosine lobe the distance blend weights rays with. Higher makes each distance texel represent a narrower cone of directions, which sharpens the visibility test at the cost of more noise.",
            visible=True,
            developer=True,
            ui_min="1.0f",
            ui_max="200.0f",
            hard_min="1.0f"
        ),
        field(
            "normal_bias",
            Float,
            added_in=1,
            default="0.15f",
            short_desc="Normal bias (m)",
            long_desc="Distance the shading point is pushed along the surface normal before probes are sampled. Counteracts self-shadowing artifacts where a surface sits almost exactly on the visibility boundary its own probes recorded.",
            visible=True,
            developer=False,
            ui_min="0.0f",
            ui_max="1.0f",
            hard_min="0.0f"
        ),
        field(
            "view_bias",
            Float,
            added_in=1,
            default="0.1f",
            short_desc="View bias (m)",
            long_desc="Distance the shading point is pushed toward the camera before probes are sampled. Together with the normal bias this is the standard DDGI surface bias; it mainly helps at grazing angles.",
            visible=True,
            developer=False,
            ui_min="0.0f",
            ui_max="1.0f",
            hard_min="0.0f"
        ),
        field(
            "intensity",
            Float,
            added_in=1,
            default="1.0f",
            short_desc="Intensity",
            long_desc="Multiplier applied to the sampled irradiance before it replaces the ambient term. 1.0 is physically neutral; other values are an artistic override.",
            visible=True,
            developer=False,
            ui_min="0.0f",
            ui_max="4.0f",
            hard_min="0.0f"
        ),
        field(
            "probes_per_frame",
            Int,
            added_in=1,
            default="512",
            short_desc="Probes per frame",
            long_desc="Per-frame update budget. Probes are updated round-robin, so a grid larger than this budget takes several frames per full sweep. Lower values cap the per-frame GPU cost at the price of slower convergence.",
            visible=True,
            developer=False,
            ui_min="1",
            ui_max="65536",
            hard_min="1"
        ),
        field(
            "relocation_enabled",
            Bool,
            added_in=1,
            default="true",
            short_desc="Probe relocation",
            long_desc="Let probes that land inside or very close to geometry move within half a grid cell toward open space. Without relocation those probes record the inside of walls and bleed dark or wrong irradiance into their neighborhood.",
            visible=True,
            developer=False
        ),
        field(
            "classification_enabled",
            Bool,
            added_in=1,
            default="true",
            short_desc="Probe classification",
            long_desc="Mark probes that see mostly backfaces (i.e. are enclosed in geometry) inactive, so they are skipped by both the update and the interpolation. Saves trace cost and stops enclosed probes from contributing.",
            visible=True,
            developer=False
        ),
        field(
            "debug_draw_probes",
            Bool,
            added_in=1,
            default="false",
            short_desc="Draw probes",
            long_desc="Draw a wire sphere at every probe position, coloured by its classification state. Debug aid for checking grid fit and relocation.",
            visible=True,
            developer=True
        ),
    ],
)
