from erhe_codegen import *

# Persisted settings of the editor's Debug Visualizations window
# (tools/debug_visualizations.cpp). Defaults match the C++ member
# defaults. Not to be confused with Debug_visualizations_config, the
# per-viewport light/camera visualization modes in Viewport_config_data.
struct("Debug_visualizations_settings",
    version=3,
    short_desc="Debug Visualizations",
    long_desc="Settings for the Debug Visualizations window",
    developer=False,
    fields=[
        field("lights",                      EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off", short_desc="Lights"),
        field("cameras",                     EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off", short_desc="Cameras"),
        field("layouts",                     EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off", short_desc="Layouts"),
        field("skins",                       EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off", short_desc="Skins"),
        field("node_axises",                 EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off", short_desc="Node Axises"),
        field("physics",                     EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off", short_desc="Physics"),
        field("raytrace",                    EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off", short_desc="Raytrace"),
        field("vertex_labels",               EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off", short_desc="Show Vertices"),
        field("facet_labels",                EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off", short_desc="Show Facets"),
        field("edge_labels",                 EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off", short_desc="Show Edges"),
        field("corner_labels",               EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off", short_desc="Show Corners"),
        field("world_axes",                        Bool,  added_in=1, default="false", short_desc="World Axes"),
        field("shadow_debug",                      Bool,  added_in=1, default="false", short_desc="Shadow Debug"),
        field("shadow_fit_debug",                  Bool,  added_in=2, default="false", short_desc="Shadow Fit",           long_desc="Master toggle for the shadow frustum fit visualizations"),
        field("shadow_fit_casters",                Bool,  added_in=2, default="false", short_desc="Fit Casters",          long_desc="Per-caster world AABBs gathered for the tight shadow frustum fit"),
        field("shadow_fit_caster_hull",            Bool,  added_in=2, default="false", short_desc="Fit Caster Hull",      long_desc="Convex hull around the caster bounds, before clipping to the shadow caster volume"),
        field("shadow_fit_receivers",              Bool,  added_in=2, default="false", short_desc="Fit Receivers",        long_desc="Receiver volume (main camera view frustum) used by the tight shadow frustum fit"),
        field("shadow_fit_volume_planes",          Bool,  added_in=2, default="false", short_desc="Fit Volume Planes",    long_desc="Shadow caster volume (F_shadow) planes"),
        field("shadow_fit_points",                 Bool,  added_in=2, default="false", short_desc="Fit Points",           long_desc="Point set the light space box was fitted to (clipped caster hull or view frustum corners)"),
        field("shadow_fit_light_plane_hull",       Bool,  added_in=2, default="false", short_desc="Fit Light Plane Hull", long_desc="2D hull on the light plane with the rotating calipers OBB and its supporting edge"),
        field("shadow_fit_box_fit",                Bool,  added_in=2, default="false", short_desc="Fit Box: Points",      long_desc="Light space box after fitting to the point set"),
        field("shadow_fit_box_frustum",            Bool,  added_in=2, default="false", short_desc="Fit Box: Frustum",     long_desc="Light space box after the view frustum / near constraints"),
        field("shadow_fit_box_cap",                Bool,  added_in=2, default="false", short_desc="Fit Box: Range Cap",   long_desc="Light space box after the shadow range cap"),
        field("shadow_fit_box_final",              Bool,  added_in=2, default="false", short_desc="Fit Box: Final",       long_desc="Final light space box after quantize and texel snap; matches the light projection"),
        # Shadow frustum fit visualization colors and line widths. Negative
        # line widths are in pixels and do not scale by distance.
        field("shadow_fit_casters_color",          Vec4,  added_in=3, default="0.7f, 0.7f, 0.7f, 0.6f", short_desc="Fit Casters Color"),
        field("shadow_fit_casters_width",          Float, added_in=3, default="1.0f",                   short_desc="Fit Casters Width"),
        field("shadow_fit_caster_hull_color",      Vec4,  added_in=3, default="1.0f, 1.0f, 1.0f, 0.8f", short_desc="Fit Caster Hull Color"),
        field("shadow_fit_caster_hull_width",      Float, added_in=3, default="1.0f",                   short_desc="Fit Caster Hull Width"),
        field("shadow_fit_receivers_color",        Vec4,  added_in=3, default="0.4f, 0.8f, 1.0f, 1.0f", short_desc="Fit Receivers Color"),
        field("shadow_fit_receivers_width",        Float, added_in=3, default="2.0f",                   short_desc="Fit Receivers Width"),
        field("shadow_fit_volume_planes_color",    Vec4,  added_in=3, default="1.0f, 0.6f, 0.0f, 0.5f", short_desc="Fit Volume Planes Color"),
        field("shadow_fit_volume_planes_width",    Float, added_in=3, default="8.0f",                   short_desc="Fit Volume Planes Width"),
        field("shadow_fit_points_color",           Vec4,  added_in=3, default="0.2f, 1.0f, 1.0f, 1.0f", short_desc="Fit Points Color"),
        field("shadow_fit_points_width",           Float, added_in=3, default="1.0f",                   short_desc="Fit Points Width"),
        field("shadow_fit_light_plane_hull_color", Vec4,  added_in=3, default="1.0f, 0.0f, 1.0f, 0.7f", short_desc="Fit Light Plane Hull Color"),
        field("shadow_fit_light_plane_hull_width", Float, added_in=3, default="2.0f",                   short_desc="Fit Light Plane Hull Width"),
        field("shadow_fit_obb_color",              Vec4,  added_in=3, default="1.0f, 0.3f, 0.6f, 1.0f", short_desc="Fit OBB Color"),
        field("shadow_fit_obb_width",              Float, added_in=3, default="1.0f",                   short_desc="Fit OBB Width"),
        field("shadow_fit_obb_edge_color",         Vec4,  added_in=3, default="0.4f, 1.0f, 0.1f, 1.0f", short_desc="Fit OBB Edge Color"),
        field("shadow_fit_obb_edge_width",         Float, added_in=3, default="3.0f",                   short_desc="Fit OBB Edge Width"),
        field("shadow_fit_box_fit_color",          Vec4,  added_in=3, default="1.0f, 0.2f, 0.2f, 1.0f", short_desc="Fit Box: Points Color"),
        field("shadow_fit_box_frustum_color",      Vec4,  added_in=3, default="1.0f, 1.0f, 0.2f, 1.0f", short_desc="Fit Box: Frustum Color"),
        field("shadow_fit_box_cap_color",          Vec4,  added_in=3, default="0.3f, 0.5f, 1.0f, 1.0f", short_desc="Fit Box: Range Cap Color"),
        field("shadow_fit_box_final_color",        Vec4,  added_in=3, default="0.2f, 1.0f, 0.2f, 1.0f", short_desc="Fit Box: Final Color"),
        field("shadow_fit_box_width",              Float, added_in=3, default="2.0f",                   short_desc="Fit Box Width"),
        field("selection",                         Bool,  added_in=1, default="true",   short_desc="Selection"),
        field("selection_bounding_points",         Bool,  added_in=1, default="false",  short_desc="Bounding Points"),
        field("selection_box",                     Bool,  added_in=1, default="false",  short_desc="Selection Box"),
        field("selection_sphere",                  Bool,  added_in=1, default="false",  short_desc="Selection Sphere"),
        field("selection_parts",                   Bool,  added_in=1, default="false",  short_desc="Selection Parts"),
        field("selection_convex_hull",             Bool,  added_in=1, default="false",  short_desc="Selection Convex Hull"),
        field("selection_convex_hull_projected",   Bool,  added_in=1, default="false",  short_desc="Selection Projected Hull"),
        field("debug_convex_hull",                 Bool,  added_in=1, default="false",  short_desc="Debug Convex Hull"),
        field("convex_hull_edge",                  Int,   added_in=1, default="0",      short_desc="Convex Hull Edge"),
        field("selection_major_color",             Vec4,  added_in=1, default="2.0f, 1.6f, 0.1f, 1.0f", short_desc="Selection Major Color"),
        field("selection_minor_color",             Vec4,  added_in=1, default="2.0f, 1.6f, 0.1f, 0.5f", short_desc="Selection Minor Color"),
        field("group_selection_major_color",       Vec4,  added_in=1, default="2.0f, 1.2f, 0.1f, 1.0f", short_desc="Group Major Color"),
        field("group_selection_minor_color",       Vec4,  added_in=1, default="2.0f, 1.2f, 0.1f, 0.5f", short_desc="Group Minor Color"),
        field("selection_major_width",             Float, added_in=1, default="4.0f",   short_desc="Selection Major Width"),
        field("selection_minor_width",             Float, added_in=1, default="2.0f",   short_desc="Selection Minor Width"),
        field("sphere_step_count",                 Int,   added_in=1, default="80",     short_desc="Sphere Step Count"),
        field("gap",                               Float, added_in=1, default="0.003f", short_desc="Gap"),
        field("tool_hide",                         Bool,  added_in=1, default="false",  short_desc="Tool Hide"),
        field("frustum_box",                       Bool,  added_in=1, default="false",  short_desc="Frustum Box"),
        field("frustum_planes",                    Bool,  added_in=1, default="false",  short_desc="Frustum Planes"),
        field("light_line_width",                  Float, added_in=1, default="8.0f",   short_desc="Light Line Width"),
        field("camera_cull_test",                  Bool,  added_in=1, default="false",  short_desc="Camera Cull Test"),
        field("camera_line_width",                 Float, added_in=1, default="8.0f",   short_desc="Camera Line Width"),
        field("camera_line_color",                 Vec4,  added_in=1, default="1.0f, 1.0f, 1.0f, 1.0f", short_desc="Camera Line Color"),
        field("layout_line_width",                 Float, added_in=1, default="2.0f",   short_desc="Layout Line Width"),
        field("layout_line_color",                 Vec4,  added_in=1, default="0.2f, 0.8f, 1.0f, 1.0f", short_desc="Layout Line Color"),
        field("max_labels",                        Int,   added_in=1, default="400",    short_desc="Max Labels"),
        field("vertex_positions",                  Bool,  added_in=1, default="false",  short_desc="Vertex Positions"),
        field("vertex_label_text_color",           Vec4,  added_in=1, default="0.3f, 1.0f, 0.3f, 1.0f", short_desc="Vertex Label Text Color"),
        field("vertex_label_line_color",           Vec4,  added_in=1, default="0.0f, 0.8f, 0.0f, 1.0f", short_desc="Vertex Label Line Color"),
        field("vertex_label_line_width",           Float, added_in=1, default="1.0f",   short_desc="Vertex Label Line Width"),
        field("vertex_label_line_length",          Float, added_in=1, default="0.1f",  short_desc="Vertex Label Line Length"),
        field("edge_label_text_color",             Vec4,  added_in=1, default="1.0f, 0.3f, 0.3f, 1.0f", short_desc="Edge Label Text Color"),
        field("edge_label_text_offset",            Float, added_in=1, default="0.1f",   short_desc="Edge Label Text Offset"),
        field("edge_label_line_color",             Vec4,  added_in=1, default="0.8f, 0.0f, 0.0f, 1.0f", short_desc="Edge Label Line Color"),
        field("edge_label_line_width",             Float, added_in=1, default="1.0f",   short_desc="Edge Label Line Width"),
        field("edge_label_line_length",            Float, added_in=1, default="0.5f",   short_desc="Edge Label Line Length"),
        field("facet_label_text_color",            Vec4,  added_in=1, default="1.0f, 1.0f, 5.0f, 1.0f", short_desc="Facet Label Text Color"),
        field("facet_label_line_color",            Vec4,  added_in=1, default="1.0f, 0.5f, 0.0f, 1.0f", short_desc="Facet Label Line Color"),
        field("facet_label_line_width",            Float, added_in=1, default="1.0f",   short_desc="Facet Label Line Width"),
        field("facet_label_line_length",           Float, added_in=1, default="0.1f",   short_desc="Facet Label Line Length"),
        field("corner_label_text_color",           Vec4,  added_in=1, default="0.5f, 1.0f, 1.0f, 1.0f", short_desc="Corner Label Text Color"),
        field("corner_label_line_color",           Vec4,  added_in=1, default="0.0f, 0.5f, 0.5f, 1.0f", short_desc="Corner Label Line Color"),
        field("corner_label_line_width",           Float, added_in=1, default="1.0f",   short_desc="Corner Label Line Width"),
        field("corner_label_line_length",          Float, added_in=1, default="0.05f",  short_desc="Corner Label Line Length"),
    ],
)
