from erhe_codegen import *

# Persisted settings of the editor's Debug Visualizations window
# (tools/debug_visualizations.cpp). Defaults match the C++ member
# defaults. Not to be confused with Debug_visualizations_config, the
# per-viewport light/camera visualization modes in Viewport_config_data.
struct("Debug_visualizations_settings",
    version=1,
    short_desc="Debug Visualizations",
    long_desc="Settings for the Debug Visualizations window",
    developer=False,
    fields=[
        field("lights",                  EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::all",      short_desc="Lights"),
        field("cameras",                 EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::selected", short_desc="Cameras"),
        field("layouts",                 EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::all",      short_desc="Layouts"),
        field("skins",                   EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off",      short_desc="Skins"),
        field("node_axises",             EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off",      short_desc="Node Axises"),
        field("physics",                 EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off",      short_desc="Physics"),
        field("raytrace",                EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off",      short_desc="Raytrace"),
        field("vertex_labels",           EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off",      short_desc="Show Vertices"),
        field("facet_labels",            EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off",      short_desc="Show Facets"),
        field("edge_labels",             EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off",      short_desc="Show Edges"),
        field("corner_labels",           EnumRef("Visualization_mode"), added_in=1, default="Visualization_mode::off",      short_desc="Show Corners"),
        field("world_axes",              Bool,  added_in=1, default="false",  short_desc="World Axes"),
        field("shadow_debug",            Bool,  added_in=1, default="false",  short_desc="Shadow Debug"),
        field("selection",               Bool,  added_in=1, default="true",   short_desc="Selection"),
        field("selection_bounding_points", Bool, added_in=1, default="false", short_desc="Bounding Points"),
        field("selection_box",           Bool,  added_in=1, default="false",  short_desc="Selection Box"),
        field("selection_sphere",        Bool,  added_in=1, default="false",  short_desc="Selection Sphere"),
        field("selection_parts",         Bool,  added_in=1, default="false",  short_desc="Selection Parts"),
        field("selection_convex_hull",   Bool,  added_in=1, default="false",  short_desc="Selection Convex Hull"),
        field("selection_convex_hull_projected", Bool, added_in=1, default="false", short_desc="Selection Projected Hull"),
        field("debug_convex_hull",       Bool,  added_in=1, default="false",  short_desc="Debug Convex Hull"),
        field("convex_hull_edge",        Int,   added_in=1, default="0",      short_desc="Convex Hull Edge"),
        field("selection_major_color",   Vec4,  added_in=1, default="2.0f, 1.6f, 0.1f, 1.0f", short_desc="Selection Major Color"),
        field("selection_minor_color",   Vec4,  added_in=1, default="2.0f, 1.6f, 0.1f, 0.5f", short_desc="Selection Minor Color"),
        field("group_selection_major_color", Vec4, added_in=1, default="2.0f, 1.2f, 0.1f, 1.0f", short_desc="Group Major Color"),
        field("group_selection_minor_color", Vec4, added_in=1, default="2.0f, 1.2f, 0.1f, 0.5f", short_desc="Group Minor Color"),
        field("selection_major_width",   Float, added_in=1, default="4.0f",   short_desc="Selection Major Width"),
        field("selection_minor_width",   Float, added_in=1, default="2.0f",   short_desc="Selection Minor Width"),
        field("sphere_step_count",       Int,   added_in=1, default="80",     short_desc="Sphere Step Count"),
        field("gap",                     Float, added_in=1, default="0.003f", short_desc="Gap"),
        field("tool_hide",               Bool,  added_in=1, default="false",  short_desc="Tool Hide"),
        field("frustum_box",             Bool,  added_in=1, default="false",  short_desc="Frustum Box"),
        field("frustum_planes",          Bool,  added_in=1, default="false",  short_desc="Frustum Planes"),
        field("light_line_width",        Float, added_in=1, default="8.0f",   short_desc="Light Line Width"),
        field("camera_cull_test",        Bool,  added_in=1, default="false",  short_desc="Camera Cull Test"),
        field("camera_line_width",       Float, added_in=1, default="8.0f",   short_desc="Camera Line Width"),
        field("camera_line_color",       Vec4,  added_in=1, default="1.0f, 1.0f, 1.0f, 1.0f", short_desc="Camera Line Color"),
        field("layout_line_width",       Float, added_in=1, default="2.0f",   short_desc="Layout Line Width"),
        field("layout_line_color",       Vec4,  added_in=1, default="0.2f, 0.8f, 1.0f, 1.0f", short_desc="Layout Line Color"),
        field("max_labels",              Int,   added_in=1, default="400",    short_desc="Max Labels"),
        field("vertex_positions",        Bool,  added_in=1, default="false",  short_desc="Vertex Positions"),
        field("vertex_label_text_color", Vec4,  added_in=1, default="0.3f, 1.0f, 0.3f, 1.0f", short_desc="Vertex Label Text Color"),
        field("vertex_label_line_color", Vec4,  added_in=1, default="0.0f, 0.8f, 0.0f, 1.0f", short_desc="Vertex Label Line Color"),
        field("vertex_label_line_width", Float, added_in=1, default="1.0f",   short_desc="Vertex Label Line Width"),
        field("vertex_label_line_length", Float, added_in=1, default="0.1f",  short_desc="Vertex Label Line Length"),
        field("edge_label_text_color",   Vec4,  added_in=1, default="1.0f, 0.3f, 0.3f, 1.0f", short_desc="Edge Label Text Color"),
        field("edge_label_text_offset",  Float, added_in=1, default="0.1f",   short_desc="Edge Label Text Offset"),
        field("edge_label_line_color",   Vec4,  added_in=1, default="0.8f, 0.0f, 0.0f, 1.0f", short_desc="Edge Label Line Color"),
        field("edge_label_line_width",   Float, added_in=1, default="1.0f",   short_desc="Edge Label Line Width"),
        field("edge_label_line_length",  Float, added_in=1, default="0.5f",   short_desc="Edge Label Line Length"),
        field("facet_label_text_color",  Vec4,  added_in=1, default="1.0f, 1.0f, 5.0f, 1.0f", short_desc="Facet Label Text Color"),
        field("facet_label_line_color",  Vec4,  added_in=1, default="1.0f, 0.5f, 0.0f, 1.0f", short_desc="Facet Label Line Color"),
        field("facet_label_line_width",  Float, added_in=1, default="1.0f",   short_desc="Facet Label Line Width"),
        field("facet_label_line_length", Float, added_in=1, default="0.1f",   short_desc="Facet Label Line Length"),
        field("corner_label_text_color", Vec4,  added_in=1, default="0.5f, 1.0f, 1.0f, 1.0f", short_desc="Corner Label Text Color"),
        field("corner_label_line_color", Vec4,  added_in=1, default="0.0f, 0.5f, 0.5f, 1.0f", short_desc="Corner Label Line Color"),
        field("corner_label_line_width", Float, added_in=1, default="1.0f",   short_desc="Corner Label Line Width"),
        field("corner_label_line_length", Float, added_in=1, default="0.05f", short_desc="Corner Label Line Length"),
    ],
)
