from erhe_codegen import *

struct("Grid_config",
    field(
        "snap_enabled",
        Bool,
        added_in=1,
        default="true",
        short_desc="",
        long_desc=""
    ),
    field(
        "visible",
        Bool,
        added_in=1,
        default="true",
        short_desc="",
        long_desc=""
    ),
    field(
        "major_color",
        Vec4,
        added_in=1,
        default="1.0f, 1.0f, 1.0f, 1.0f",
        short_desc="",
        long_desc=""
    ),
    field(
        "minor_color",
        Vec4,
        added_in=1,
        default="0.5f, 0.5f, 0.5f, 0.5f",
        short_desc="",
        long_desc=""
    ),
    field(
        "major_width",
        Float,
        added_in=1,
        default="4.0f",
        short_desc="",
        long_desc=""
    ),
    field(
        "minor_width",
        Float,
        added_in=1,
        default="2.0f",
        short_desc="",
        long_desc=""
    ),
    field(
        "cell_size",
        Float,
        added_in=1,
        default="1.0f",
        short_desc="",
        long_desc=""
    ),
    field(
        "cell_div",
        Int,
        added_in=1,
        default="10",
        short_desc="",
        long_desc=""
    ),
    field(
        "cell_count",
        Int,
        added_in=1,
        default="2",
        short_desc="",
        long_desc=""
    ),
    version=1,
)
