from erhe_codegen import *

struct("Headset_config",
    version=1,
    short_desc="",
    long_desc="",
    fields=[
        field(
            "openxr",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc=""
        ),
        field(
            "openxr_mirror",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc=""
        ),
        field(
            "quad_view",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc=""
        ),
        field(
            "debug",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc=""
        ),
        field(
            "validation",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc=""
        ),
        field(
            "api_dump",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc=""
        ),
        field(
            "depth",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc=""
        ),
        field(
            "visibility_mask",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc=""
        ),
        field(
            "hand_tracking",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc=""
        ),
        field(
            "passthrough_fb",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc=""
        ),
        field(
            "composition_alpha",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc=""
        ),
    ],
)
