from erhe_codegen import *

struct("Headset_config",
    version=1,
    short_desc="Virtual Reality Headset",
    long_desc="",
    developer=False,
    fields=[
        field(
            "openxr",
            Bool,
            added_in=1,
            default="false",
            short_desc="OpenXR Enable",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "openxr_mirror",
            Bool,
            added_in=1,
            default="false",
            short_desc="OpenXR Mirror Window",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "quad_view",
            Bool,
            added_in=1,
            default="false",
            short_desc="Enable Quad View (Varjo)",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "debug",
            Bool,
            added_in=1,
            default="false",
            short_desc="Enable OpenXR Debug",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "validation",
            Bool,
            added_in=1,
            default="false",
            short_desc="Enable OpenXR Validation",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "api_dump",
            Bool,
            added_in=1,
            default="false",
            short_desc="Enable OpenXR API Dump",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "depth",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "visibility_mask",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "hand_tracking",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "passthrough_fb",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "composition_alpha",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
    ],
)
