from erhe_codegen import *

struct("Hotbar_config",
    version=1,
    short_desc="",
    long_desc="",
    fields=[
        field(
            "enabled",
            Bool,
            added_in=1,
            default="true",
            short_desc="",
            long_desc="",
            visible=True
        ),
        field(
            "show",
            Bool,
            added_in=1,
            default="true",
            short_desc="",
            long_desc="",
            visible=True
        ),
        field(
            "use_radial",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True
        ),
        field(
            "x",
            Float,
            added_in=1,
            default="0.0f",
            short_desc="",
            long_desc="",
            visible=True
        ),
        field(
            "y",
            Float,
            added_in=1,
            default="-0.140f",
            short_desc="",
            long_desc="",
            visible=True
        ),
        field(
            "z",
            Float,
            added_in=1,
            default="-0.5f",
            short_desc="",
            long_desc="",
            visible=True
        ),
    ],
)
