from erhe_codegen import *

struct("Hotbar_config",
    field(
        "enabled",
        Bool,
        added_in=1,
        default="true",
        short_desc="",
        long_desc=""
    ),
    field(
        "show",
        Bool,
        added_in=1,
        default="true",
        short_desc="",
        long_desc=""
    ),
    field(
        "use_radial",
        Bool,
        added_in=1,
        default="false",
        short_desc="",
        long_desc=""
    ),
    field(
        "x",
        Float,
        added_in=1,
        default="0.0f",
        short_desc="",
        long_desc=""
    ),
    field(
        "y",
        Float,
        added_in=1,
        default="-0.140f",
        short_desc="",
        long_desc=""
    ),
    field(
        "z",
        Float,
        added_in=1,
        default="-0.5f",
        short_desc="",
        long_desc=""
    ),
    version=1,
    short_desc="",
    long_desc="",
)
