from erhe_codegen import *

struct("Hud_config",
    version=1,
    short_desc="HUD",
    long_desc="HUD is intended for Virtual Reality - It can show ImGui UI in VR surface",
    developer=False,
    fields=[
        field(
            "enabled",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "show",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "locked",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "width",
            Int,
            added_in=1,
            default="1024",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "height",
            Int,
            added_in=1,
            default="1024",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "ppm",
            Float,
            added_in=1,
            default="5000.0f",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "x",
            Float,
            added_in=1,
            default="-0.09f",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "y",
            Float,
            added_in=1,
            default="0.0f",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "z",
            Float,
            added_in=1,
            default="-0.38f",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
    ],
)
