from erhe_codegen import *

struct("Hud_config",
    field(
        "enabled",
        Bool,
        added_in=1,
        default="false",
        short_desc="",
        long_desc=""
    ),
    field(
        "show",
        Bool,
        added_in=1,
        default="false",
        short_desc="",
        long_desc=""
    ),
    field(
        "locked",
        Bool,
        added_in=1,
        default="false",
        short_desc="",
        long_desc=""
    ),
    field(
        "width",
        Int,
        added_in=1,
        default="1024",
        short_desc="",
        long_desc=""
    ),
    field(
        "height",
        Int,
        added_in=1,
        default="1024",
        short_desc="",
        long_desc=""
    ),
    field(
        "ppm",
        Float,
        added_in=1,
        default="5000.0f",
        short_desc="",
        long_desc=""
    ),
    field(
        "x",
        Float,
        added_in=1,
        default="-0.09f",
        short_desc="",
        long_desc=""
    ),
    field(
        "y",
        Float,
        added_in=1,
        default="0.0f",
        short_desc="",
        long_desc=""
    ),
    field(
        "z",
        Float,
        added_in=1,
        default="-0.38f",
        short_desc="",
        long_desc=""
    ),
    version=1,
    short_desc="",
    long_desc="",
)
