from erhe_codegen import *

struct("Network_config",
    field(
        "upstream_address",
        String,
        added_in=1,
        default='"127.0.0.1"',
        short_desc="",
        long_desc=""
    ),
    field(
        "upstream_port",
        Int,
        added_in=1,
        default="34567",
        short_desc="",
        long_desc=""
    ),
    field(
        "downstream_address",
        String,
        added_in=1,
        default='"0.0.0.0"',
        short_desc="",
        long_desc=""
    ),
    field(
        "downstream_port",
        Int,
        added_in=1,
        default="34567",
        short_desc="",
        long_desc=""
    ),
    version=1,
    short_desc="",
    long_desc="",
)
