from erhe_codegen import *

struct("Physics_config",
    version=1,
    short_desc="",
    long_desc="",
    developer=False,
    fields=[
        field(
            "static_enable",
            Bool,
            added_in=1,
            default="true",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "dynamic_enable",
            Bool,
            added_in=1,
            default="true",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
    ],
)
