from erhe_codegen import *

struct("Radiance_cascades_config",
    reflect=True,
    version=4,
    short_desc="Radiance Cascades",
    long_desc="World-space radiance cascades (doc/editor/radiance_cascades.md): a second producer of the indirect diffuse probe field, selected with the Indirect Diffuse source. Cascade 0 is a probe grid fitted to the padded content bounding box; every next cascade has probes at the centres of 2x2x2 blocks of the one below, doubled octahedral resolution and a doubled radiance interval. The field's sampling parameters (irradiance / distance texels, biases, intensity) are the DDGI settings. Requires GPU ray query support.",
    developer=False,
    fields=[
        field(
            "probe_spacing_m",
            Float,
            added_in=1,
            default="0.5f",
            short_desc="Cascade 0 probe spacing (m)",
            long_desc="Target world-space distance s0 between adjacent cascade 0 probes. Each higher cascade doubles it. The actual spacing per axis is the box extent divided by the resulting probe count, and it grows when the probe budget or the texture size limit requires.",
            visible=True,
            developer=False,
            ui_min="0.1f",
            ui_max="8.0f",
            hard_min="0.01f"
        ),
        field(
            "volume_padding_m",
            Float,
            added_in=1,
            default="1.0f",
            short_desc="Volume padding (m)",
            long_desc="Amount the content bounding box is grown by on every side before cascade 0 is fitted, so surfaces on the box boundary still have probes on both sides.",
            visible=True,
            developer=False,
            ui_min="0.0f",
            ui_max="16.0f",
            hard_min="0.0f"
        ),
        field(
            "max_probes_cascade0",
            Int,
            added_in=1,
            default="65536",
            short_desc="Max cascade 0 probes",
            long_desc="Upper bound on the cascade 0 probe count. When the spacing would produce more probes, the spacing is scaled up until the grid fits. Every higher cascade has about 1/8 of the probes of the one below.",
            visible=True,
            developer=False,
            ui_min="8",
            ui_max="262144",
            hard_min="8"
        ),
        field(
            "max_cascades",
            Int,
            added_in=1,
            default="8",
            short_desc="Max cascades",
            long_desc="Upper bound on the cascade count. Cascades are added until the top cascade has at most 2 probes on its longest axis, or this many exist.",
            visible=True,
            developer=False,
            ui_min="1",
            ui_max="12",
            hard_min="1",
            hard_max="12"
        ),
        field(
            "cascade0_tile_texels",
            Int,
            added_in=1,
            default="4",
            short_desc="Cascade 0 tile texels",
            long_desc="Octahedral tile side q0 of cascade 0: q0 x q0 directions per cascade 0 probe. Cascade i uses q0 x 2^i.",
            visible=True,
            developer=True,
            ui_min="2",
            ui_max="16",
            hard_min="1",
            hard_max="64"
        ),
        field(
            "interval_scale",
            Float,
            added_in=1,
            default="1.0f",
            short_desc="Interval scale",
            long_desc="Cascade 0 interval length r0 = interval_scale x sqrt(3) x s0; cascade i covers [r0 (2^i - 1), r0 (2^(i+1) - 1)]. At least 1, so any wall between a surface and a cascade 0 probe of its cell lies within cascade 0's interval.",
            visible=True,
            developer=True,
            ui_min="1.0f",
            ui_max="4.0f",
            hard_min="1.0f"
        ),
        field(
            "texels_per_frame",
            Int,
            added_in=2,
            default="65536",
            short_desc="Texels per frame",
            long_desc="Per-frame trace budget: raw atlas texels (one interval ray each) traced per frame. A cursor walks all cascades, cascade 0 first, so a layout with more texels than this takes several frames per full refresh. Lower values cap the per-frame GPU cost at the price of slower convergence.",
            visible=True,
            developer=False,
            ui_min="256",
            ui_max="4194304",
            hard_min="1"
        ),
        field(
            "hysteresis",
            Float,
            added_in=2,
            default="0.9f",
            short_desc="Hysteresis",
            long_desc="Temporal blend weight kept from the previous raw interval each time a texel is traced. 0 replaces the texel with the new trace. A texel traced for the first time since its atlas was allocated is written without blending.",
            visible=True,
            developer=False,
            ui_min="0.0f",
            ui_max="0.999f",
            hard_min="0.0f",
            hard_max="0.999f"
        ),
        field(
            "merge_mode",
            EnumRef("Radiance_cascades_merge_mode"),
            added_in=4,
            default="Radiance_cascades_merge_mode::interpolate",
            short_desc="Merge mode",
            long_desc="How a cascade merges with the cascade above: interpolate blends the 8 surrounding upper probes trilinearly; visibility_masked skips the upper probes the probe cannot see or that sit inside geometry (a visibility pass runs when the layout or the scene geometry changes). Edited with the Radiance Cascades window's combo.",
            visible=False,
            developer=True
        ),
        field(
            "debug_cascade_mask",
            Int,
            added_in=3,
            default="0",
            short_desc="Debug cascade mask",
            long_desc="Debug view of the interval bands: bit i set zeroes cascade i's radiance in the merge while its transparency is kept, so the merged atlases show only the unmasked bands (bit 12 masks the sky beyond the top cascade). 0 merges everything. Edited with the Radiance Cascades window's checkboxes.",
            visible=False,
            developer=True,
            ui_min="0",
            ui_max="8191",
            hard_min="0",
            hard_max="8191"
        ),
    ],
)
