from erhe_codegen import *

struct("Viewport_config_data",
    version=1,
    short_desc="",
    long_desc="",
    developer=False,
    fields=[
        field(
            "gizmo_scale",
            Float,
            added_in=1,
            default="3.0f",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "polygon_fill",
            Bool,
            added_in=1,
            default="true",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "edge_lines",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "selection_polygon_fill",
            Bool,
            added_in=1,
            default="true",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "selection_edge_lines",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "corner_points",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "polygon_centroids",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "selection_bounding_box",
            Bool,
            added_in=1,
            default="true",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "selection_bounding_sphere",
            Bool,
            added_in=1,
            default="true",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "edge_color",
            Vec4,
            added_in=1,
            default="0.0f, 0.0f, 0.0f, 0.5f",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "selection_edge_color",
            Vec4,
            added_in=1,
            default="0.0f, 0.0f, 0.0f, 0.5f",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "clear_color",
            Vec4,
            added_in=1,
            default="0.1f, 0.2f, 0.4f, 1.0f",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
    ],
)
