from erhe_codegen import *

struct("Window_config",
    field(
        "show",
        Bool,
        added_in=1,
        default="true",
        short_desc="",
        long_desc=""
    ),
    field(
        "fullscreen",
        Bool,
        added_in=1,
        default="false",
        short_desc="",
        long_desc=""
    ),
    field(
        "use_transparency",
        Bool,
        added_in=1,
        default="false",
        short_desc="",
        long_desc=""
    ),
    field(
        "gl_major",
        Int,
        added_in=1,
        default="4",
        short_desc="",
        long_desc=""
    ),
    field(
        "gl_minor",
        Int,
        added_in=1,
        default="6",
        short_desc="",
        long_desc=""
    ),
    field(
        "size",
        IVec2,
        added_in=1,
        default="1920, 1080",
        short_desc="",
        long_desc=""
    ),
    field(
        "color_bit_depth",
        Int,
        added_in=1,
        default="8",
        short_desc="",
        long_desc=""
    ),
    field(
        "high_pixel_density",
        Bool,
        added_in=1,
        default="true",
        short_desc="",
        long_desc=""
    ),
    field(
        "use_finish",
        Bool,
        added_in=1,
        default="false",
        short_desc="",
        long_desc=""
    ),
    field(
        "use_sleep",
        Bool,
        added_in=1,
        default="false",
        short_desc="",
        long_desc=""
    ),
    field(
        "sleep_margin",
        Float,
        added_in=1,
        default="0.0f",
        short_desc="",
        long_desc=""
    ),
    field(
        "swap_interval",
        Int,
        added_in=1,
        default="0",
        short_desc="",
        long_desc=""
    ),
    field(
        "enable_joystick",
        Bool,
        added_in=1,
        default="true",
        short_desc="",
        long_desc=""
    ),
    version=1,
)
