from erhe_codegen import *

struct("Window_config",
    version=3,
    short_desc="",
    long_desc="",
    developer=False,
    fields=[
        field(
            "show",
            Bool,
            added_in=1,
            default="true",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "fullscreen",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "exclusive_fullscreen",
            Bool,
            added_in=2,
            default="false",
            short_desc="Exclusive Fullscreen",
            long_desc="Request exclusive fullscreen mode (Windows Vulkan, VK_EXT_full_screen_exclusive, application controlled). Used only when fullscreen is also true; ignored otherwise and on platforms/drivers without the extension. Bypasses DWM composition, which changes presentation timing behavior - useful for frame pacing testing (windowed vs fullscreen comparison).",
            visible=True,
            developer=False
        ),
        field(
            "refreshrate",
            Float,
            added_in=3,
            default="0.0f",
            short_desc="Fullscreen Refresh Rate",
            long_desc="Requested display refresh rate in Hz for fullscreen mode (0 = keep the desktop default). Used only when fullscreen is true. The closest available fullscreen mode at the desktop resolution is selected; the available modes and rates are listed in the log at window creation (frame pacing testing: pick e.g. 23.976, 60 or 120 Hz without touching OS display settings).",
            visible=True,
            developer=False
        ),
        field(
            "use_transparency",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "gl_major",
            Int,
            added_in=1,
            default="4",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "gl_minor",
            Int,
            added_in=1,
            default="6",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "size",
            IVec2,
            added_in=1,
            default="1920, 1080",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "color_bit_depth",
            Int,
            added_in=1,
            default="8",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "high_pixel_density",
            Bool,
            added_in=1,
            default="true",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "use_finish",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "use_sleep",
            Bool,
            added_in=1,
            default="false",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "sleep_margin",
            Float,
            added_in=1,
            default="0.0f",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "swap_interval",
            Int,
            added_in=1,
            default="0",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "enable_joystick",
            Bool,
            added_in=1,
            default="true",
            short_desc="",
            long_desc="",
            visible=True,
            developer=False
        ),
        field(
            "power_save",
            Bool,
            added_in=2,
            default="true",
            short_desc="Power Save",
            long_desc="Render at a reduced frequency when the window is unfocused or not visible, and pause the simulation while not visible",
            visible=True,
            developer=False
        ),
        field(
            "unfocused_fps",
            Int,
            added_in=2,
            default="30",
            short_desc="Unfocused FPS",
            long_desc="Frame rate cap while the window is visible but does not have input focus (power_save only)",
            visible=True,
            developer=False
        ),
        field(
            "hidden_fps",
            Int,
            added_in=2,
            default="10",
            short_desc="Hidden FPS",
            long_desc="Frame rate cap while the window is not visible (minimized, occluded or hidden); rendering and simulation are skipped (power_save only)",
            visible=True,
            developer=False
        ),
    ],
)
