cmake ^
    -G "Visual Studio 17 2022" ^
    -A x64 ^
    -B build ^
    -S . ^
    -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ^
    -Wno-dev ^
    -DERHE_FONT_RASTERIZATION_LIBRARY=freetype ^
    -DERHE_GLTF_LIBRARY=cgltf ^
    -DERHE_GUI_LIBRARY=imgui ^
    -DERHE_PHYSICS_LIBRARY=jolt ^
    -DERHE_PNG_LIBRARY=mango ^
    -DERHE_PROFILE_LIBRARY=tracy ^
    -DERHE_RAYTRACE_LIBRARY=bvh ^
    -DERHE_SVG_LIBRARY=lunasvg ^
    -DERHE_TEXT_LAYOUT_LIBRARY=harfbuzz ^
    -DERHE_WINDOW_LIBRARY=glfw ^
    -DERHE_XR_LIBRARY=none
