# Writes the erhe_version translation unit (script mode, run by the
# erhe_version_stamp target at every build and once at configure time):
#   cmake -DERHE_VERSION_OUTPUT=<version.cpp> -DERHE_PROJECT_VERSION=<x.y>
#         -DERHE_SOURCE_DIR=<source tree> -P generate_version.cmake
# The file is replaced only when its content changes (configure_file
# COPYONLY), so a build with an unchanged commit recompiles nothing.

if (NOT ERHE_VERSION_OUTPUT OR NOT ERHE_PROJECT_VERSION OR NOT ERHE_SOURCE_DIR)
    message(FATAL_ERROR "generate_version.cmake: ERHE_VERSION_OUTPUT, ERHE_PROJECT_VERSION and ERHE_SOURCE_DIR are required")
endif ()

set(ERHE_GIT_DESCRIBE "unknown")
find_package(Git QUIET)
if (GIT_FOUND AND EXISTS "${ERHE_SOURCE_DIR}/.git")
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" describe --tags --always --dirty
        WORKING_DIRECTORY "${ERHE_SOURCE_DIR}"
        OUTPUT_VARIABLE erhe_git_describe_output
        ERROR_QUIET
        RESULT_VARIABLE erhe_git_describe_result
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if (erhe_git_describe_result EQUAL 0 AND NOT erhe_git_describe_output STREQUAL "")
        set(ERHE_GIT_DESCRIBE "${erhe_git_describe_output}")
    endif ()
endif ()

set(erhe_version_content "// Generated by src/erhe/version/generate_version.cmake - do not edit.
#include \"erhe_version/version.hpp\"

namespace erhe::version {

auto get_project_version() -> const char*
{
    return \"${ERHE_PROJECT_VERSION}\";
}

auto get_git_describe() -> const char*
{
    return \"${ERHE_GIT_DESCRIBE}\";
}

auto get_description() -> const char*
{
    return \"erhe ${ERHE_PROJECT_VERSION} (${ERHE_GIT_DESCRIBE})\";
}

} // namespace erhe::version
")

set(erhe_version_staging "${ERHE_VERSION_OUTPUT}.staging")
file(WRITE "${erhe_version_staging}" "${erhe_version_content}")
configure_file("${erhe_version_staging}" "${ERHE_VERSION_OUTPUT}" COPYONLY)
file(REMOVE "${erhe_version_staging}")
