# jemalloc for ERHE_MALLOC_LIBRARY=jemalloc
#
# jemalloc has no CMake build - it is an autoconf project. The git tag carries
# only configure.ac (autogen.sh needs autoconf), so the release tarball of the
# same tag, which ships the generated configure script, is fetched instead.
#
# Two steps:
#  1. At configure time, jemalloc's configure script runs once (out of tree,
#     in ${CMAKE_BINARY_DIR}/jemalloc_configure) to generate the platform
#     headers (jemalloc.h, jemalloc_internal_defs.h, ...). It needs a POSIX
#     sh with the usual text tools; on Windows the one bundled with Git for
#     Windows is used, and the MSVC environment (cl/clang-cl, INCLUDE, LIB)
#     must be active, which the scripts\configure_*.bat wrappers provide.
#  2. The library sources are compiled into the static target
#     `erhe_jemalloc` with the regular erhe toolchain (runtime library,
#     sanitizers and optimization flags follow the rest of the build).
#
# erhe uses jemalloc through the `je_` symbol prefix on every platform:
# C malloc/free are left untouched, and erhe_profile routes the global C++
# operator new/delete to je_* (src/erhe/profile/erhe_profile/profile.cpp).
# The private-symbol namespace (normally generated by jemalloc's Makefile from
# nm output) is not generated: JEMALLOC_NO_PRIVATE_NAMESPACE is defined, as
# jemalloc's own msvc static-library projects do.

set(ERHE_JEMALLOC_VERSION "5.3.1")

CPMAddPackage(
    NAME          jemalloc
    VERSION       ${ERHE_JEMALLOC_VERSION}
    URL           https://github.com/jemalloc/jemalloc/releases/download/${ERHE_JEMALLOC_VERSION}/jemalloc-${ERHE_JEMALLOC_VERSION}.tar.bz2
    DOWNLOAD_ONLY YES
)

# --- Step 1: run configure to generate headers ------------------------------

if (WIN32)
    find_package(Git QUIET)
    set(_erhe_jemalloc_sh_hints "")
    if (GIT_EXECUTABLE)
        get_filename_component(_erhe_git_dir "${GIT_EXECUTABLE}" DIRECTORY)
        list(APPEND _erhe_jemalloc_sh_hints "${_erhe_git_dir}/../usr/bin" "${_erhe_git_dir}/../bin")
    endif ()
    find_program(
        ERHE_JEMALLOC_SH
        NAMES sh
        HINTS ${_erhe_jemalloc_sh_hints}
        PATHS "$ENV{ProgramFiles}/Git/usr/bin"
        NO_DEFAULT_PATH
    )
    if (NOT ERHE_JEMALLOC_SH)
        find_program(ERHE_JEMALLOC_SH NAMES sh)
    endif ()
else ()
    find_program(ERHE_JEMALLOC_SH NAMES sh)
endif ()
if (NOT ERHE_JEMALLOC_SH)
    message(FATAL_ERROR "ERHE_MALLOC_LIBRARY=jemalloc needs a POSIX sh to run jemalloc's configure script (on Windows: install Git for Windows)")
endif ()

# configure is given the compiler by file name with its directory prepended to
# PATH: a full path to e.g. cl.exe contains spaces, which configure's CC does
# not survive.
get_filename_component(_erhe_jemalloc_cc_dir  "${CMAKE_C_COMPILER}" DIRECTORY)
get_filename_component(_erhe_jemalloc_cc_name "${CMAKE_C_COMPILER}" NAME)

set(_erhe_jemalloc_configure_args
    --with-jemalloc-prefix=je_
    --disable-cxx
    --disable-prof
    --disable-libdl
)
if (APPLE)
    # With the je_ prefix erhe calls jemalloc explicitly; do not register it
    # as the default malloc zone.
    list(APPEND _erhe_jemalloc_configure_args --disable-zone-allocator)
endif ()

set(ERHE_JEMALLOC_CONFIGURE_DIR "${CMAKE_BINARY_DIR}/jemalloc_configure")
set(_erhe_jemalloc_stamp_content "${ERHE_JEMALLOC_VERSION};${CMAKE_C_COMPILER};${_erhe_jemalloc_configure_args}")
set(_erhe_jemalloc_stamp_file "${ERHE_JEMALLOC_CONFIGURE_DIR}/erhe_configure_stamp.txt")
set(_erhe_jemalloc_stamp_previous "")
if (EXISTS "${_erhe_jemalloc_stamp_file}")
    file(READ "${_erhe_jemalloc_stamp_file}" _erhe_jemalloc_stamp_previous)
endif ()

if ((NOT _erhe_jemalloc_stamp_previous STREQUAL _erhe_jemalloc_stamp_content) OR
    (NOT EXISTS "${ERHE_JEMALLOC_CONFIGURE_DIR}/include/jemalloc/jemalloc.h"))
    message(STATUS "Running jemalloc configure (once per build tree; takes about a minute on Windows)")
    file(REMOVE_RECURSE "${ERHE_JEMALLOC_CONFIGURE_DIR}")
    file(MAKE_DIRECTORY "${ERHE_JEMALLOC_CONFIGURE_DIR}")
    if (WIN32)
        set(_erhe_jemalloc_path "${_erhe_jemalloc_cc_dir};$ENV{PATH}")
    else ()
        set(_erhe_jemalloc_path "${_erhe_jemalloc_cc_dir}:$ENV{PATH}")
    endif ()
    execute_process(
        COMMAND ${CMAKE_COMMAND} -E env
            "PATH=${_erhe_jemalloc_path}"
            "CC=${_erhe_jemalloc_cc_name}"
            ${ERHE_JEMALLOC_SH} "${jemalloc_SOURCE_DIR}/configure" ${_erhe_jemalloc_configure_args}
        WORKING_DIRECTORY "${ERHE_JEMALLOC_CONFIGURE_DIR}"
        RESULT_VARIABLE   _erhe_jemalloc_result
        OUTPUT_FILE       "${ERHE_JEMALLOC_CONFIGURE_DIR}/erhe_configure_output.txt"
        ERROR_FILE        "${ERHE_JEMALLOC_CONFIGURE_DIR}/erhe_configure_output.txt"
    )
    if (NOT _erhe_jemalloc_result EQUAL 0)
        message(FATAL_ERROR "jemalloc configure failed (${_erhe_jemalloc_result}); see ${ERHE_JEMALLOC_CONFIGURE_DIR}/erhe_configure_output.txt and config.log")
    endif ()
    file(WRITE "${_erhe_jemalloc_stamp_file}" "${_erhe_jemalloc_stamp_content}")
endif ()

# --- Step 2: static library -------------------------------------------------

# C_SRCS of jemalloc's Makefile.in
set(_erhe_jemalloc_sources
    arena.c
    background_thread.c
    base.c
    bin.c
    bin_info.c
    bitmap.c
    buf_writer.c
    cache_bin.c
    ckh.c
    conf.c
    counter.c
    ctl.c
    decay.c
    div.c
    ecache.c
    edata.c
    edata_cache.c
    ehooks.c
    emap.c
    eset.c
    exp_grow.c
    extent.c
    extent_dss.c
    extent_mmap.c
    fxp.c
    hook.c
    hpa.c
    hpa_central.c
    hpa_hooks.c
    hpa_utils.c
    hpdata.c
    inspect.c
    jemalloc.c
    large.c
    log.c
    malloc_io.c
    mutex.c
    nstime.c
    pa.c
    pa_extra.c
    pac.c
    pages.c
    peak_event.c
    prof.c
    prof_data.c
    prof_log.c
    prof_recent.c
    prof_stack_range.c
    prof_stats.c
    prof_sys.c
    psset.c
    rtree.c
    safety_check.c
    san.c
    san_bump.c
    sc.c
    sec.c
    stats.c
    sz.c
    tcache.c
    test_hooks.c
    thread_event.c
    thread_event_registry.c
    ticker.c
    tsd.c
    util.c
    witness.c
)
list(TRANSFORM _erhe_jemalloc_sources PREPEND "${jemalloc_SOURCE_DIR}/src/")

add_library(erhe_jemalloc STATIC ${_erhe_jemalloc_sources})
set_target_properties(erhe_jemalloc PROPERTIES FOLDER "third_party")

# The configure output directory must come first: the release tarball also
# carries headers generated on the release machine in its own include/.
target_include_directories(erhe_jemalloc SYSTEM PUBLIC "${ERHE_JEMALLOC_CONFIGURE_DIR}/include")
target_include_directories(erhe_jemalloc SYSTEM PUBLIC "${jemalloc_SOURCE_DIR}/include")
target_compile_definitions(erhe_jemalloc PRIVATE _REENTRANT JEMALLOC_NO_PRIVATE_NAMESPACE)

if (MSVC)
    target_include_directories(erhe_jemalloc SYSTEM PUBLIC "${jemalloc_SOURCE_DIR}/include/msvc_compat")
    # Static library: no __declspec(dllimport) on the public API.
    target_compile_definitions(erhe_jemalloc PUBLIC JEMALLOC_EXPORT=)
    # Third-party C sources: warnings are upstream's concern.
    target_compile_options(erhe_jemalloc PRIVATE /W0)
else ()
    if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
        target_compile_definitions(erhe_jemalloc PRIVATE _GNU_SOURCE)
    endif ()
    target_compile_options(erhe_jemalloc PRIVATE -w)
    set(THREADS_PREFER_PTHREAD_FLAG ON)
    find_package(Threads REQUIRED)
    target_link_libraries(erhe_jemalloc PUBLIC Threads::Threads)
endif ()
