function (FetchContent_MakeAvailable_taskflow)
    FetchContent_GetProperties(taskflow)
    string(TOLOWER "taskflow" lc_taskflow)
    if (NOT ${lc_taskflow}_POPULATED)
        FetchContent_Populate(taskflow)
        option(TF_BUILD_TESTS "Enables builds of tests" OFF)
        option(TF_BUILD_EXAMPLES "Enables builds of examples" OFF)
        add_subdirectory(${${lc_taskflow}_SOURCE_DIR} ${${lc_taskflow}_BINARY_DIR})
    endif ()
endfunction()
