auto {WRAPPER_NAME}({WRAPPER_ARGUMENTS}) -> {WRAPPER_RETURN_TYPE}
{{
#if defined(ERHE_LOG_GL_FUNCTIONS)
    log_gl->trace(
        "{NATIVE_NAME}({LOG_FORMAT_STRING})"{LOG_FORMAT_ENTRY_SEPARATOR}
        {LOG_FORMAT_ENTRIES}
    );
#endif
    {CAPTURE_RESULT}{NATIVE_NAME}({ARGUMENT_LIST});
    ERHE_CHECK_GL_ERRORS
{WRAPPER_RETURN_STATEMENT}}}
